### ISSUE TITLE
waidTillFileLoad function does not work and causes big  bugs

### ISSUE THREAD

**Issue by Mubtasimf443** [Mubtasimf443/Awaiter.js#1]
## waidTillFileLoad  
 waidTillFileLoad function does not work and causes big  bugs

### code
```
  await waidTillFileLoad({
                filePath: imagePath
              });
``` 

### error 

```
file:///C:/git/Client%20Project/gojushinryo/sv/node_modules/awaiter.js/index.js:25
                if (checkingTime.toString()!== 'NaN') {
                                 ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at file:///C:/git/Client%20Project/gojushinryo/sv/node_modules/awaiter.js/index.js:25:34
    at new Promise (<anonymous>)
    at waidTillFileLoad (file:///C:/git/Client%20Project/gojushinryo/sv/node_modules/awaiter.js/index.js:19:12)
    at file:///C:/git/Client%20Project/gojushinryo/sv/_lib/model_base_function/Testimonials.js:59:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.15.0
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by Mubtasimf443** [comment]
## This issue is because you do not have use awaiter.js version 1.0.2 correctly ,


#### please write the correct code 

```
 await waidTillFileLoad({
                filePath: imagePath,
                checkingTime :50
              });
```

**Comment by Mubtasimf443** [comment]
In the awaiter.js version 1.0.2 , checkingTime is compulsory, but in version 1.0.3 it is not compulsory
